name: Run self test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    name: Testing on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.11', '3.12', '3.13' ]
        include:
          - os: ubuntu-22.04
            python-version: '3.10'
          - os: ubuntu-22.04
            python-version: '3.9'
          - os: ubuntu-22.04
            python-version: '3.8'

          - os: macos-latest
            python-version: '3.10'
          - os: macos-latest
            python-version: '3.9'
          - os: macos-latest
            python-version: '3.8'

          - os: windows-latest
            python-version: '3.10'
          - os: windows-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.8'
    steps:
      - uses: actions/checkout@v4
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for pypy3
        if: ${{ matrix.python-version == 'pypy3' }}
        run: pypy3 -m pip install -e .[dev]
      - name: Install dependencies for CPython
        if: ${{ matrix.python-version != 'pypy3' }}
        run: python3 -m pip install -e .[dev]
      - name: Run tests using Cpython
        if: ${{ matrix.python-version != 'pypy3' }}
        run: pytest
      - name: Run tests using Pypy
        if: ${{ matrix.python-version == 'pypy3' }}
        run: pytest

